<?php echo $this->render('partials/layout-before.phtml'); // BEFORE ////////////////////////////////// ?>

<form name="register" action="<?php $this->eurl('user/sign-up'); ?>" method="post" data-remote>
  <input type="text" name="name" placeholder="Imię i nazwisko" value="Karol Kochan<?php //$this->formVal('name');?>" required/>
  <input type="email" name="email" placeholder="Adres e-mail" value="karolkochan@gmail.com<?php //$this->formVal('email');?>" required/>
  <input type="password" name="pwd" placeholder="Hasło" value="karol" required/>
  <input type="password" name="pwd_repeat" placeholder="Powtórz hasło" value="karol" required/>
  <button type="submit" name="submit" value="ok">Zarejestruj</button>
</form>
<p>Jeżeli posiadasz już konto w systemie <a href="<?php $this->eurl('user/sign-in');?>" data-remote>zaloguj się.</a> </p>

<?php echo $this->render('partials/layout-middle.phtml'); // MIDDLE ////////////////////////////////// ?>

<?php echo $this->render('partials/layout-after.phtml'); // AFTER //////////////////////////////////// ?>