<?php echo $this->render('partials/layout-before.phtml'); // BEFORE ////////////////////////////////// ?>

<div class="group avatar">
	<a href="<?php $this->eurl('dashboard');?>" data-remote></a>
	<p><?php echo $this->user_['name'];?> <span><a href="<?php $this->eurl('user/sign-out');?>" data-remote>wyloguj</a></span></p>
	<div class="avatar">
		<img src="<?php echo $this->avatar($this->user_);?>" alt="<?php echo $this->user_['name'];?>"/>
	</div>
</div>
<div class="group lr">
	<h4>Dokumenty </h4>
	<div class="left" data-ttip="Prace które są podejrzewane o plagiat">
		<a href="<?php $this->eurl('dashboard/documents/alert');?>" data-remote></a>
		<span>7</span>
		<h5>Podejrzanych </h5>
	</div>
	<div class="right" data-ttip="Wszystkie prace dodane przez Ciebie do systemu">
		<a href="<?php $this->eurl('dashboard/documents');?>" data-remote></a>
		<span>52</span>
		<h5>Wszystkich </h5>
	</div>
</div>
<div class="group add">
	<h3><span>Prześlij dokument</span><?php $this->svg('graphics/icons/document-create.svg');?></h3>
	<a href="<?php $this->eurl('dashboard/documents/create');?>" data-remote></a>
</div>
<?php if(App_Auth::getInstance()->isAdmin()) { ?>
<div class="group pending-users" style="margin-top: 50px;">
	<h3>Oczekują na akceptację</h3>
	<div class="pending">
		<ul>
			<?php foreach($this->users_pending as $item) { ?>
			<li>
				<a href="<?php $this->eurl('dashboard/users/show/'.$item['_id']);?>" data-ttip="<?php echo $item['email'];?>" data-ttip-time="0" data-remote></a>
				<img src="<?php echo $this->avatar($item);?>" alt=""/>
			</li>
			<?php } ?>
		</ul>
		<div class="more"></div>
	</div>
</div>
<div class="group lr">
	<div class="left" data-ttip="Użytkownicy posiadającymi uprawnienia administratora">
		<a href="<?php $this->eurl('dashboard/users?role=3');?>" data-remote></a>
		<span><?php echo $this->users_admin_count;?></span>
		<h5>Administratorów </h5>
	</div>
	<div class="right" data-ttip="Wszyscy użytkownicy w systemie">
		<a href="<?php $this->eurl('dashboard/users');?>" data-remote></a>
		<span><?php echo $this->users_all_count;?></span>
		<h5>Wszystkich </h5>
	</div>
</div>
<div class="group add">
	<h3><span>Dodaj użytkownika</span><?php $this->svg('graphics/icons/user-create.svg');?></h3>
	<a href="<?php $this->eurl('dashboard/users/create');?>" data-remote></a>
</div>
<?php } ?>

<?php echo $this->render('partials/layout-middle.phtml'); // MIDDLE ////////////////////////////////// ?>

<?php echo $this->render('partials/layout-after.phtml'); // AFTER //////////////////////////////////// ?>