<?php echo $this->render('partials/layout-before.phtml'); // BEFORE ////////////////////////////////// ?>

<?php echo $this->render('partials/history-back.phtml'); // HISTORY BACK //// ?>

<form name="register" action="<?php $this->eurl('dashboard/documents/create'); ?>" method="post" enctype="multipart/form-data" data-remote>
<div class="group">
  	<?php 
      $this->Input('text', 'title', 'Temat pracy', $this->formVal('title'), true, 'emp no-line', true);
      $this->Input('text', 'author', 'Autor', $this->formVal('author'), true);
      $this->Input('email', 'email', 'E-mail autora', $this->formVal('email'));
      $this->Input('document', 'document', 'Wybierz dokument', '', true);
      $this->InputRadio('type', 'Typ dokumentu', array(
    			'thesis'=>'Praca',
    			'book'=>'Książka' 
    		),'thesis');
      $this->Input('submit', 'submit', 'Prześlij pracę', 'ok');
    ?>
</div>
</form>

<?php echo $this->render('partials/layout-middle.phtml'); // MIDDLE ////////////////////////////////// ?>

<div class="content-filler"></div>

<?php echo $this->render('partials/layout-after.phtml'); // AFTER //////////////////////////////////// ?>