<?php echo $this->render('partials/layout-before.phtml'); // BEFORE ////////////////////////////////// ?>

<?php echo $this->render('partials/history-back.phtml'); // HISTORY BACK //// ?>

<?php if(App_Auth::getInstance()->isAdmin() || App_Auth::getInstance()->isSelf($this->document['_owner'])) { ?>
<form name="document_data_change" action="<?php $this->eurl('dashboard/documents/update/'.$this->document['_id']); ?>" method="post" enctype="multipart/form-data" data-remote>
<div class="group">
    <?php 
    	$this->Input('text', 'title', 'Tytuł pracy', $this->document['title'], true, 'emp no-line');
		$this->Input('text', 'author', 'Autor', $this->document['author'], true);
		$this->Input('email', 'email', 'E-mail', $this->document['email']);
		if(App_Auth::getInstance()->isAdmin() || App_Auth::getInstance()->isSelf($this->document['_owner'])) {
			$this->InputRadio('action', 'Akcja', array(
	  				'1'=>'-', 
	  				'0'=>array('Usuń dokument','destroy','graphics/icons/destroy.svg')
	  			),'1');
		}
		$this->Input('submit', 'submit', 'Zapisz zmiany', 'ok');
	?>
</div>
</form>
<?php } ?>

<?php echo $this->render('partials/layout-middle.phtml'); // MIDDLE ////////////////////////////////// ?>

<?php echo $this->render('documents/show-content.phtml'); ?>

<?php echo $this->render('partials/layout-after.phtml'); // AFTER //////////////////////////////////// ?>