<?php echo $this->render('partials/layout-before.phtml'); // BEFORE ////////////////////////////////// ?>

<?php echo $this->render('partials/history-back.phtml'); // HISTORY BACK //// ?>

<form name="register" action="<?php $this->eurl('dashboard/users/create'); ?>" method="post" enctype="multipart/form-data" data-remote>
<div class="group">
  	<?php 
  		$this->Input('text', 'name', 'Imię i nazwisko', $this->formVal('name'), true, 'emp no-line', true);
  		$this->Input('email', 'email', 'Adres e-mail', $this->formVal('email'), true);
  		$this->Input('image', 'avatar', 'Wybierz zdjęcie');
  		$this->InputRadio('role', 'Uprawnienia', array(
				'3'=>'Administrator', 
				'2'=>'Promotor', 
				'1'=>'Zawieszony', 
			),'2');
  		$this->Input('submit', 'submit', 'Dodaj użytkownika', 'ok');
  	?>
</div>
</form>

<?php echo $this->render('partials/layout-middle.phtml'); // MIDDLE ////////////////////////////////// ?>

<div class="content-filler"></div>

<?php echo $this->render('partials/layout-after.phtml'); // AFTER //////////////////////////////////// ?>