<?php echo $this->render('partials/layout-before.phtml'); // BEFORE ////////////////////////////////// ?>

<?php echo $this->render('partials/history-back.phtml'); // HISTORY BACK //// ?>

<form name="users_filter" action="<?php $this->eurl('dashboard/users'); ?>" method="get" data-remote>
<div class="group">
  	<?php 
  		$this->Input('text', 'search', 'Imię, nazwisko lub e-mail', $this->formVal('search'), false, 'ic ic-search');
  		$this->InputCheckbox('role','Typ:',array(
  				'3'=>'Administrator', 
  				'2'=>'Promotor',
  				'1'=>'Zawieszony'
  			),$this->formVal('role'));
  		$this->Input('submit', 'submit', 'Filtruj wyniki', 'ok');
  	?>
</div>
</form>

<?php echo $this->render('partials/layout-middle.phtml'); // MIDDLE ////////////////////////////////// ?>

<div class="block user-mini">
	<ul>
		<?php if($this->users->count()>0) { foreach($this->users as $user) { ?>
		<li>
			<a href="<?php $this->eurl('dashboard/users/show/'.$user['_id']); ?>" data-remote></a>
			<h4><?php echo $user['name'];?> <span><a href="mailto:<?php echo $user['email'];?>"><?php echo $user['email'];?></a></span></h4>
			<div class="avatar">
				<img src="<?php echo $this->avatar($user);?>" alt="Karol Kochan">
			</div>
		</li>
		<?php } } else { ?>
		<li class="empty">
			<h4>Brak wyników</h4>
		</li>
		<?php } ?>
	</ul>
</div>

<?php echo $this->render('partials/layout-after.phtml'); // AFTER //////////////////////////////////// ?>