<?php echo $this->render('partials/layout-before.phtml'); // BEFORE ////////////////////////////////// ?>

<?php echo $this->render('partials/history-back.phtml'); // HISTORY BACK //// ?>

<?php if(App_Auth::getInstance()->isAdmin() || App_Auth::getInstance()->isSelf($this->user['_id'])) { ?>
<form name="user_data_change" action="<?php $this->eurl('dashboard/users/update/'.$this->user['_id']); ?>" method="post" enctype="multipart/form-data" data-remote>
<div class="group">
	<?php 
    $this->Input('text', 'name', 'Imię i nazwisko', $this->user['name'], true, 'emp');
    $this->Input('email', 'email', 'E-mail', $this->user['email'], true);
    $this->Input('image', 'avatar', 'Wybierz zdjęcie');

    if(App_Auth::getInstance()->isAdmin()) {
      $this->InputRadio('role', 'Uprawnienia', array(
          '3'=>'Administrator', 
          '2'=>'Promotor', 
          '1'=>'Zawieszony', 
          '0'=>array('Usuń konto','destroy','graphics/icons/destroy.svg')
        ),$this->user['role']);
    } else if(App_Auth::getInstance()->isSelf($this->user['_id'])) {
      $this->InputRadio('action', 'Akcja', array(
          '1'=>'-', 
          '0'=>array('Usuń konto','destroy','graphics/icons/destroy.svg')
        ),'1');
    }
    $this->Input('submit', 'submit', 'Zapisz zmiany', 'ok');
  ?>
</div>
</form>
<?php } ?>

<?php echo $this->render('partials/layout-middle.phtml'); // MIDDLE ////////////////////////////////// ?>

<div class="block user">
	<img src="<?php echo $this->avatar($this->user);?>" alt=""/>
	<h2><?php echo $this->user['name'];?> </h2>
	<h3><a href="mailto:<?php echo $this->user['email'];?>"><?php echo $this->user['email'];?></a> </h3>
</div>

<div class="block header line"><h3>Dokumenty użytkownika </h3></div>
<div class="block percent-chart">
  <div class="chart" data-chart data-percent-connected-off="comparisons" data-percent='[
    {"label":"Alert","value":<?php echo $this->documents_count_alert;?>,"color":"alert"},
    {"label":"Warning","value":<?php echo $this->documents_count_warning;?>,"color":"warning"},
    {"label":"Clean","value":<?php echo $this->documents_count_clean;?>,"color":"ok"}]'>
  </div>
  <h4 data-connected="comparisons"><?php echo $this->documents_count_alert+$this->documents_count_warning+$this->documents_count_clean; ?></h4>
</div>
<div class="block results-mini">
  <ul>
    <?php if(count($this->documents)>0) { foreach($this->documents as $document) { 
      $level = $document['maxSimilarity'];//isset($comparison['result']['percentageSimilarity']) ? $comparison['result']['percentageSimilarity'] : 0;
    ?>
    <li>
      <a href="<?php $this->eurl('dashboard/documents/show/'.$document['_id']);?>" data-remote>
        <?php $this->statusInfo($level, true, true); ?>
      </a>
      <div class="doc">
        <span><?php echo $document['title'];?></span>
      </div>
    </li>
    <?php } } else { ?>
    <li class="empty">
      <h4>Brak dokumentów</h4>
    </li>
    <?php } ?>
  </ul>
</div>

<?php echo $this->render('partials/layout-after.phtml'); // AFTER //////////////////////////////////// ?>